name: Trigger auto deployment for miabe-startshot-1-aca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/miabe-startshot-1-aca-AutoDeployTrigger-2a0c51a6-4769-4102-899b-3a675d89b94e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MIABESTARTSHOT1ACA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MIABESTARTSHOT1ACA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MIABESTARTSHOT1ACA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistrymea2ouwrb6uiu.azurecr.io
          registryUsername: ${{ secrets.MIABESTARTSHOT1ACA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MIABESTARTSHOT1ACA_REGISTRY_PASSWORD }}
          containerAppName: miabe-startshot-1-aca
          resourceGroup: reactbasic96b6starshotbd88
          imageToBuild: containerregistrymea2ouwrb6uiu.azurecr.io/miabe-startshot-1-aca:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


